import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';
import { Clock3, Navigation, PackageCheck, Radio, UserRound } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import CampusRouteMap from './components/CampusRouteMap';
const API='http://localhost:3003';
export default function DeliveryTracking(){const {id}=useParams();const {api}=useAuth();const [data,setData]=useState();const [campus,setCampus]=useState();const [route,setRoute]=useState();const load=async()=>{const [tracking,campusData,routeData]=await Promise.allSettled([api.get(`/api/delivery/${id}/tracking`),api.get('/api/campus'),api.get(`/api/delivery/${id}/route`)]);if(tracking.status==='fulfilled')setData(tracking.value.data);if(campusData.status==='fulfilled')setCampus(campusData.value.data);if(routeData.status==='fulfilled')setRoute(routeData.value.data.route||routeData.value.data);};useEffect(()=>{load();const socket=io(API,{auth:{token:localStorage.getItem('token')}});socket.emit('delivery:join',id);socket.on('delivery:location',location=>setData(current=>({...current,location})));socket.on('delivery:status',update=>setData(current=>({...current,delivery:{...current?.delivery,status:update.status}})));return()=>socket.close();},[id]);if(!data||!campus)return <main className="mx-auto w-full max-w-[1240px] px-5 sm:px-7 lg:px-10 py-16"><div className="h-[30rem] animate-pulse rounded-3xl bg-ink/5"/></main>;const delivery=data.delivery;const pickup=route?.coordinates?.[0];const destination=route?.coordinates?.at(-1);const cards=[[PackageCheck,'Status',delivery.status?.replaceAll('_',' ')],[UserRound,'Delivery partner',delivery.courier_name||'Finding a partner'],[Navigation,'Current checkpoint',data.location?'Live location received':'Waiting for location'],[Clock3,'Estimated arrival',delivery.estimated_time||`${route?.etaMinutes||'—'} min`]];return <main className="min-h-screen bg-paper pb-16"><header className="border-b border-ink/10"><div className="mx-auto w-full max-w-[1240px] px-5 sm:px-7 lg:px-10 py-9"><span className="text-[.68rem] font-extrabold uppercase tracking-[.16em] text-mesh-600 flex items-center gap-1"><Radio size={13}/> Live campus tracking</span><h1 className="mt-3 font-display text-5xl font-semibold">Your delivery is {delivery.status?.replaceAll('_',' ').toLowerCase()}.</h1><p className="mt-3 text-sm text-ink/50">{delivery.item_description||delivery.listing_title||'Campus order'} · {delivery.drop_location}</p></div></header><div className="mx-auto w-full max-w-[1240px] px-5 sm:px-7 lg:px-10 grid gap-5 py-6 lg:grid-cols-[1fr_320px]"><CampusRouteMap campus={campus} route={route} position={data.location} pickup={pickup} destination={destination}/><aside className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{cards.map(([Icon,label,value])=><article key={label} className="rounded-[1.6rem] border border-mesh-900/10 bg-white shadow-[0_10px_40px_rgba(35,58,40,.06)] flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-mesh-50 text-mesh-700"><Icon size={19}/></span><div><span className="text-[.68rem] font-extrabold uppercase tracking-[.16em] text-mesh-600">{label}</span><b className="mt-1 block text-sm">{value}</b></div></article>)}</aside></div></main>}

