import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { io } from 'socket.io-client';
import { Clock3, Navigation, PackageCheck, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import CampusMap from '../components/CampusMap';
import './DeliveryTracking.css';
const API='http://localhost:3003';
export default function DeliveryTracking(){const {id}=useParams();const {user}=useAuth();const token=localStorage.getItem('token');const [data,setData]=useState();const [campus,setCampus]=useState();const load=async()=>{const h={Authorization:`Bearer ${token}`};const [t,c]=await Promise.all([fetch(`${API}/api/delivery/${id}/tracking`,{headers:h}).then(r=>r.json()),fetch(`${API}/api/campus`,{headers:h}).then(r=>r.json())]);setData(t);setCampus(c)};useEffect(()=>{load();const s=io(API,{auth:{token}});s.emit('delivery:join',id);s.on('delivery:location',location=>setData(d=>({...d,location})));s.on('delivery:status',x=>setData(d=>({...d,delivery:{...d.delivery,status:x.status}})));return()=>s.close()},[id]);if(!data||!campus)return <main className="tracking-load">Loading live delivery…</main>;const d=data.delivery;return <main className="tracking"><header><span>CampusMesh · Live tracking</span><h1>Your delivery is {d.status?.replaceAll('_',' ').toLowerCase()}.</h1><p>{d.item_description||d.listing_title||'Campus order'} · {d.drop_location}</p></header><div className="tracking-grid"><CampusMap campus={campus} current={data.location} pickup={campus.buildings.find(b=>b.name===d.pickup_location?.split(' · ')[0])} destination={campus.buildings.find(b=>b.name===d.drop_location?.split(' · ')[0])}/><aside><div><PackageCheck/><b>Status</b><strong>{d.status?.replaceAll('_',' ')}</strong></div><div><UserRound/><b>Delivery partner</b><strong>{d.courier_name||'Finding a partner'}</strong></div><div><Navigation/><b>Current location</b><strong>{data.location?`${Math.round(data.location.speed||0)} km/h · live`:'Waiting for partner location'}</strong></div><div><Clock3/><b>Estimated arrival</b><strong>{d.estimated_time||'6 min'}</strong></div></aside></div></main>}
